### ISSUE TITLE
autoFixOnSave takes multiple saves to finish

### ISSUE THREAD

**Issue by robyoder** [Microsoft/vscode-tslint#295]
This is different from #294. In this case, I've disabled my other extension, so the only extra formatter here is tslint.

### tslint.json

```json
{
	"rules": {
		"no-consecutive-blank-lines": true,
		"semicolon": true
	}
}
```

### vscode settings

```json
{
	"files.insertFinalNewline": true,
	"tslint.autoFixOnSave": true
}
```

### test.ts

```js
console.log("foo")


console.log("bar")

console.log("baz")
```

I can't indicate it here, but there's no newline at the end of test.ts. So the cursor is at the end of the last line there.

### Results

![three-saves](https://user-images.githubusercontent.com/622513/32963875-9a6b86e4-cb8e-11e7-984a-52f0c2a60c7a.gif)

1. VS Code inserts a blank line at the end of the file. TSLint does nothing.
2. TSLint removes the extra blank line and adds semicolons to the last two, but not the first one.
3. TSLint adds the semicolon to the first line.

All three of these steps should happen the first time I save the file.

**Comment by egamma** [comment]
Looks like this is issue/comment https://github.com/Microsoft/vscode-tslint/issues/164#issuecomment-300822033.

**Comment by KayUOM** [comment]
Im also experiecing this problem. I have to Cntrl + S multiple times for it to fix all of the autofix problems.

**Comment by PapyElGringo** [comment]
Any news on it?

**Comment by egamma** [comment]
Documenting the limitation and the workaround will happen soon.

The real fix is more involved since this needs to happen during the blocking  `TextDocumentWillSaveEvent.waitUntil()` event. A repeated validation can take an arbitrary long time, but we do not want to block for an arbitrary time the extension host.

**Comment by PapyElGringo** [comment]
Ok thanks for the update, Im tryting to create as workaround an extension that will chain-call tslint.fixAllProblems 5 times before saving the document but it's trigger an error.

> Failed to apply TSLint fixes to the document. Please consider opening an issue with steps to reproduce.

Any idea?

**Comment by egamma** [comment]
Nice try, but this approach will not work. 

After the non overlapping fixes are applied once you must re-lint the document to get up to date positions for the overlapping fixes that could not be fixed. otherwise the positions become stale and the edits cannot be applied.

**Comment by PapyElGringo** [comment]
Maybe I can programatically relint between 2 tslint.fixAllProblems?

Do you have any other idea for workaround ?

**Comment by egamma** [comment]
>Maybe I can programatically relint between 2 tslint.fixAllProblems?

Relinting is not exposed to other extensions, sorry. 

The best work around is still that the user presses CTRL+S until all auto fixable issues are fixed. What could be improved in the UI for this is that there is an indication in the status bar that not all auto fixable rule failures could be fixed due to overlapping changes. Then the user presses CTRL+S until this indication is gone. 

My understanding is that overlapping auto fixes are rather rare, do they happen for you all the time?

**Comment by PapyElGringo** [comment]
We have a lot for now because we are beautifying all our existing coee with new rules.

But maybe in a classic development process it's happen less.

One of my best example is : ``` var hello = "hello"``` with our new rules var will be changed in let and then in const and the quote will be changed at the first fix

**Comment by egamma** [comment]
This is a good example and I see the pain. 

In this case you would have to press CTRL+S, three times, this is not pleasant but would work correct?

**Comment by PapyElGringo** [comment]
Yeah beside this issue it's work very well. Who will be able to improve the behavior?

**Comment by egamma** [comment]
This needs support on the VS Code API side to support that there is away for an extension to negotiate how long the `TextDocumentWillSaveEvent.waitUntil()` will wait for an extension before it continues. This is not on top of our API backlog and not clear whether this door should opened.

There are other options to solve the immediate pain, you can call tslint with --fix on the command line. You can imagine an extension that provides a command that does this or that runs this. Since this modifies the entire file this will have other negative consequences (e.g. break points will be shifted etc.).

**Comment by PapyElGringo** [comment]
Ok it's clear.
Im just wondering why the beautifier like Beautify or Prettier don't have the same limitation?

**Comment by cancerberoSgx** [comment]
I think this problem was solved - same happened to me and I tried cloning this repository and debugging  with the latest extension sources I cannot reproduce the issue anymore :)  BTW tslint --fix did the work. I think at some point you have upgraded the dependency but forgot to publish the new version in the marketplace, please do !

**Comment by egamma** [comment]
I could still reproduce the problem and I´ve no fixed the problem. The fix will be in 1.0.30.
